"""Shared DuckDB schema and write-batch settings."""

SCHEMA_VERSION = 17
STAGING_ROW_BATCH_SIZE = 1_000
QUALITY_ROW_BATCH_SIZE = 1_000
TRANSFORMATION_IMPACT_ROW_BATCH_SIZE = 1_000
NORMALIZATION_ROW_BATCH_SIZE = 1_000
