"""Compatibility exports for split web helpers."""

from .target_readers import (
    _missing_schema_reader_message,
    _read_model_catalog,
    _read_readiness_snapshots,
    _read_schema,
    _relationship_value_choices,
    _selected_local_profile,
    _source_value_choices,
    _target_credential_id,
    _test_connection,
)
from .forms import (
    _bounded_request_body,
    _checked,
    _form_values,
    _is_json_request,
    _mapping_request_form,
    _optional_int,
    _optional_nonnegative_query_int,
    _positive_query_int,
    _revision,
    _secure_form,
    _split_models,
    _submitted_model_scope,
    _text,
    _texts,
    _validate_mapping_form_pairs,
    _value_mappings_from_form,
)
from .presenters.common import _flash, _plain_ui_error, _project_error, _render
from .presenters.summary import (
    _quality_summary_url,
    _render_normalization,
    _render_summary,
    _render_target,
    _require_local_stack_access,
    _require_local_stack_start,
    _require_local_stack_stop,
    _summary_rows_url,
)
from .presenters.schema import (
    _dataset_choices,
    _decode_delimiter,
    _manual_schema_boolean,
    _manual_schema_fields,
    _manual_schema_models,
    _model_matches_application_scope,
    _related_dataset_name_default,
    _render_derived_entities,
    _render_schema,
    _schema_key_views,
    _schema_model_choices,
)
from .presenters.mapping import (
    _active_mapping_definition,
    _available_mapping_business_keys,
    _business_key_id,
    _canonical_mapping_type,
    _comma_values,
    _display_mapping_value,
    _draft_or_redirect,
    _manager_quality_rules_from_form,
    _mapping_allowed_fields,
    _mapping_dataset_views,
    _mapping_datasets_from_form,
    _mapping_field_page_size,
    _mapping_return_url,
    _mapping_save_error_response,
    _mapping_source_samples,
    _merge_partial_mapping_datasets,
    _quality_check_view,
    _related_business_keys,
    _render_mapping,
    _resolver_business_key,
    _safe_spreadsheet_text,
    _scalar_mapping_preview,
    _standard_reference_business_key,
    _target_catalog_resolver,
    _transformation_impact_evidence,
    _transformation_impact_filters,
    _transformation_impact_identity,
    _transformation_impact_labels,
    _transformation_impact_url,
    _value_mappings_json,
)

__all__ = ['_test_connection', '_selected_local_profile', '_missing_schema_reader_message', '_read_schema', '_read_model_catalog', '_read_readiness_snapshots', '_source_value_choices', '_relationship_value_choices', '_target_credential_id', '_secure_form', '_is_json_request', '_mapping_request_form', '_bounded_request_body', '_validate_mapping_form_pairs', '_value_mappings_from_form', '_optional_nonnegative_query_int', '_positive_query_int', '_revision', '_text', '_form_values', '_split_models', '_submitted_model_scope', '_texts', '_checked', '_optional_int', '_render', '_plain_ui_error', '_project_error', '_flash', '_render_target', '_render_normalization', '_render_summary', '_summary_rows_url', '_quality_summary_url', '_require_local_stack_access', '_require_local_stack_start', '_require_local_stack_stop', '_manual_schema_models', '_manual_schema_fields', '_manual_schema_boolean', '_decode_delimiter', '_dataset_choices', '_render_derived_entities', '_related_dataset_name_default', '_schema_model_choices', '_model_matches_application_scope', '_render_schema', '_schema_key_views', '_mapping_save_error_response', '_transformation_impact_evidence', '_transformation_impact_identity', '_transformation_impact_labels', '_transformation_impact_filters', '_transformation_impact_url', '_mapping_return_url', '_mapping_field_page_size', '_render_mapping', '_mapping_dataset_views', '_quality_check_view', '_manager_quality_rules_from_form', '_value_mappings_json', '_mapping_source_samples', '_scalar_mapping_preview', '_display_mapping_value', '_safe_spreadsheet_text', '_mapping_allowed_fields', '_mapping_datasets_from_form', '_active_mapping_definition', '_merge_partial_mapping_datasets', '_standard_reference_business_key', '_related_business_keys', '_available_mapping_business_keys', '_target_catalog_resolver', '_resolver_business_key', '_canonical_mapping_type', '_comma_values', '_business_key_id', '_draft_or_redirect']
