from __future__ import annotations

import json
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile
import unittest
from unittest.mock import patch
import zipfile

from scripts.internal_release import (
    LOCK_FILE,
    REQUIRED_RELEASE_TOOLS,
    ReleaseGateError,
    _release_manifest,
    _require_locked_runtime_environment,
    _unexpected_secret_candidates,
    _validate_lock,
    _validate_wheel_contents,
)


ROOT = Path(__file__).resolve().parents[1]


class InternalReleaseGateTests(unittest.TestCase):
    def test_checked_in_windows_python_312_lock_is_complete(self) -> None:
        _validate_lock(LOCK_FILE)

    def test_release_toolchain_is_exactly_pinned(self) -> None:
        project = (ROOT / "pyproject.toml").read_text(encoding="utf-8")
        self.assertIn('requires = ["setuptools==83.0.0"]', project)
        for distribution, expected in REQUIRED_RELEASE_TOOLS.items():
            self.assertIn(f'"{distribution}=={expected}"', project)

    def test_lock_rejects_unhashed_or_unpinned_dependencies(self) -> None:
        with tempfile.TemporaryDirectory(dir=ROOT / ".tmp") as temporary:
            lock = Path(temporary) / "requirements.lock"
            lock.write_text(
                "# autogenerated by pip-compile with Python 3.12\n"
                "--only-binary :all:\n"
                "unsafe>=1\n",
                encoding="utf-8",
            )
            with self.assertRaisesRegex(ReleaseGateError, "not exactly pinned"):
                _validate_lock(lock)

    def test_release_environment_must_match_the_runtime_lock(self) -> None:
        with tempfile.TemporaryDirectory(dir=ROOT / ".tmp") as temporary:
            lock = Path(temporary) / "requirements.lock"
            lock.write_text("example-package==1.2.3 \\\n", encoding="utf-8")
            with (
                patch(
                    "scripts.internal_release.package_version",
                    return_value="1.2.2",
                ),
                self.assertRaisesRegex(ReleaseGateError, "does not match"),
            ):
                _require_locked_runtime_environment(lock)

    def test_secret_gate_accepts_only_reviewed_false_positives(self) -> None:
        candidate = {
            "type": "Secret Keyword",
            "hashed_secret": "abc123",
            "line_number": 7,
        }
        scan = {"results": {"tests\\example.py": [candidate]}}
        baseline = {
            "results": {
                "tests/example.py": [{**candidate, "is_secret": False}],
            }
        }
        self.assertEqual(_unexpected_secret_candidates(scan, baseline), [])

        baseline["results"]["tests/example.py"][0]["is_secret"] = True
        unexpected = _unexpected_secret_candidates(scan, baseline)
        self.assertEqual(unexpected[0]["filename"], "tests\\example.py")

    def test_release_manifest_hashes_each_promoted_artifact(self) -> None:
        with tempfile.TemporaryDirectory(dir=ROOT / ".tmp") as temporary:
            artifact = Path(temporary) / "impodo.whl"
            artifact.write_bytes(b"wheel evidence")
            with patch("scripts.internal_release.sys.version_info") as version_info:
                version_info.major = 3
                version_info.minor = 12
                version_info.micro = 10
                manifest = _release_manifest(
                    release_id="impodo-0.0.0-123456789abc",
                    version="0.0.0",
                    revision="123456789abcdef",
                    artifacts=(artifact,),
                )
        self.assertEqual(manifest["source_revision"], "123456789abcdef")
        self.assertEqual(manifest["python"], "3.12.10")
        self.assertEqual(manifest["artifacts"][0]["bytes"], 14)
        self.assertRegex(manifest["artifacts"][0]["sha256"], r"^[0-9a-f]{64}$")

    def test_wheel_content_allowlist_rejects_a_stale_package(self) -> None:
        with tempfile.TemporaryDirectory(dir=ROOT / ".tmp") as temporary:
            wheel = Path(temporary) / "impodo.whl"
            with zipfile.ZipFile(wheel, "w") as archive:
                archive.writestr("impodo/project_security.py", "")
                archive.writestr("impodo/web/launcher.py", "")
                archive.writestr("impodo-0.0.0.dist-info/METADATA", "")
                archive.writestr("uc_migration_profiler/__init__.py", "")

            with self.assertRaisesRegex(ReleaseGateError, "unexpected paths"):
                _validate_wheel_contents(wheel)

    def test_internal_installer_verifies_artifacts_before_creating_venv(self) -> None:
        installer = (
            ROOT / "scripts" / "install-internal-release.ps1"
        ).read_text(encoding="utf-8")
        verify_offset = installer.index("Get-FileHash")
        create_offset = installer.index("py -3.12 -m venv")
        self.assertLess(verify_offset, create_offset)
        self.assertIn("--require-hashes", installer)
        self.assertIn("--only-binary=:all:", installer)
        self.assertIn("The bundle contains an unlisted artifact", installer)
        self.assertIn("The Impodo wheel is not covered", installer)
        self.assertNotIn("Remove-Item", installer)

    @unittest.skipUnless(sys.platform == "win32", "Windows release installer")
    def test_internal_installer_rejects_an_unlisted_artifact(self) -> None:
        with tempfile.TemporaryDirectory(dir=ROOT / ".tmp") as temporary:
            bundle = Path(temporary) / "bundle"
            bundle.mkdir()
            shutil.copy2(
                ROOT / "scripts" / "install-internal-release.ps1",
                bundle / "install-internal-release.ps1",
            )
            for name in (
                "requirements.windows-py312.lock",
                "tests.txt",
                "secret-scan.json",
                "dependency-audit.json",
                "sbom.cdx.json",
                "impodo-0.0.0-py3-none-any.whl",
            ):
                (bundle / name).write_text("release evidence\n", encoding="utf-8")

            artifacts = tuple(bundle.iterdir())
            manifest = _release_manifest(
                release_id="impodo-0.0.0-123456789abc",
                version="0.0.0",
                revision="123456789abcdef",
                artifacts=artifacts,
            )
            (bundle / "release-manifest.json").write_text(
                json.dumps(manifest),
                encoding="utf-8",
            )
            (bundle / "unexpected.txt").write_text("not governed\n", encoding="utf-8")
            install_root = Path(temporary) / "install"

            completed = subprocess.run(
                (
                    "powershell.exe",
                    "-NoProfile",
                    "-NonInteractive",
                    "-File",
                    str(bundle / "install-internal-release.ps1"),
                    "-BundleDirectory",
                    str(bundle),
                    "-InstallRoot",
                    str(install_root),
                ),
                check=False,
                capture_output=True,
                text=True,
                encoding="utf-8",
                errors="replace",
            )

            self.assertNotEqual(completed.returncode, 0)
            self.assertIn(
                "The bundle contains an unlisted artifact: unexpected.txt",
                completed.stderr,
            )
            self.assertFalse(install_root.exists())
